kind: pipeline
name: default

steps:
  - name: prepare
    image: busybox
    pull: if-not-exists
    when:
      branch:
        - master
        - dev  
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: docker-prod
    image: plugins/docker
    pull: if-not-exists
    when:
      branch:
        - master
    settings:
      repo: registry.amodosoluciones.net/${DRONE_REPO}
      registry: registry.amodosoluciones.net
      tags:
        - latest
      use_cache: true
      purge: false
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password


volumes:
  - name: cache
    temp:
      medium: default
      