workflows:
  build_android_ios:
    name: Build APK and IPA
    environment:
      node: 16
    scripts:
      - echo "Instalando dependencias de Node.js"
      - npm ci
      - echo "Configurando permisos para Gradlew"
      - cd android
      - ls -la # Comando de depuración
      - chmod +x gradlew
      - echo "Compilando APK para Android"
      - ./gradlew assembleRelease
      - cd ..
      - echo "Instalando CocoaPods"
      - sudo gem install cocoapods
      - echo "Instalando dependencias de iOS con CocoaPods"
      - cd ios/App
      - pod install
      - echo "Compilando IPA para iOS"
      - xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath App.xcarchive archive
      - xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/*.ipa
