workflows:
  build_android_ios:
    name: Build APK and IPA with Docker
    environment:
      image: docker:20.10.16 # Imagen base con Docker preinstalado
      vars:
        DOCKER_USERNAME: "uiregistry"
        DOCKER_PASSWORD: "Cn4Ukh6bHcGuJL"
    scripts:
      - apk add --no-cache docker-cli # Instala Docker CLI en caso de ser necesario
      - echo "$DOCKER_PASSWORD" | docker login registry.amodosoluciones.net -u "$DOCKER_USERNAME" --password-stdin
      - docker pull registry.amodosoluciones.net/amodosoluciones/laravel-capacitor:latest
      - docker run --rm -v $PWD:/app registry.amodosoluciones.net/amodosoluciones/laravel-capacitor:latest sh -c "
        npm install &&
        npx cap sync &&
        cd android &&
        ./gradlew assembleRelease &&
        cd ../ios/App &&
        xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath App.xcarchive archive &&
        xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist"
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/*.ipa
