workflows:
  build_android_ios:
    name: Build APK and IPA
    environment:
      node: 18
    scripts:
      - echo "Instalando dependencias de Node.js"
      - npm ci
      - echo "Verificando el contenido del directorio raíz"
      - ls -la
      - echo "Accediendo a la carpeta android"
      - cd android || echo "Error: No se pudo acceder a la carpeta android"
      - echo "Verificando contenido de android"
      - ls -la
      - echo "Configurando permisos para Gradlew"
      - chmod +x gradlew
      - echo "Verificando versiones de Java y Gradle"
      - java -version
      - ./gradlew --version
      - echo "Compilando APK para Android"
      - ./gradlew assembleRelease --stacktrace || echo "Error: La compilación de Android falló"
      - cd ..
      - echo "Instalando CocoaPods"
      - sudo gem install cocoapods
      - echo "Instalando dependencias de iOS con CocoaPods"
      - cd ios/App
      - pod install
      - echo "Compilando IPA para iOS"
      - xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath App.xcarchive archive
      - xcodebuild -exportArchive -archivePath App.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
      - ios/App/*.ipa
